#!/bin/bash

# Apt dependencies
sudo apt-get install \
                     flex \
                     bison \
                     build-essential \
                     csh \
                     libxaw7-dev \

# File dependencies
#wget http://spark-university.s3.amazonaws.com/stanford-compilers/vm/student-dist.tar.gz
#tar -xf student-dist.tar.gz
#ln -s /usr/class/cs143/cool ~/cr_compilers/cool

# Setup the class directory for provided code
if ! [ -d "class" ]; then
    mkdir -p class && cd !$
    tar -xf ../student-dist.tar.gz
fi

echo "If not done already, add /usr/class/cs143/cool/bin to your path"
