#!/bin/bash

# Apt dependencies
sudo apt-get install \
                     flex \
                     bison \
                     build-essential \
                     csh \
                     libxaw7-dev \

# File dependencies
sudo mkdir /usr/class
sudo chown $USER /usr/class
cd /usr/class
wget http://spark-university.s3.amazonaws.com/stanford-compilers/vm/student-dist.tar.gz
tar -xf student-dist.tar.gz
ln -s /usr/class/cs143/cool ~/cr_compilers/cool


echo "If not done already, add /usr/class/cs143/cool/bin to your path"
