guard :shell do
    watch(%r{(cool\.flex)}) do
        system('make lexer')
    end

    watch(%r{(lexer|\.cl)$}) do
        system('clear')
        system('./pa1-grading.pl')
        system('cat grading/test-output/backslash.diff')
    end
end
